[build]
  publish = "dist"
  command = "npm run build"
  functions = "netlify/functions"

[[headers]]
  for = "/*.js"
  [headers.values]
    "Content-Type" = "application/javascript; charset=utf-8"

[[headers]]
  for = "/*.mjs"
  [headers.values]
    "Content-Type" = "application/javascript; charset=utf-8"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200